
dataset_dir: "/home/andre/Workspace/Datasets/DML_CARINA/data"
map_dir: "/home/andre/Workspace/Datasets/DML_CARINA/map"
init_route_id: 0
init_position: 2.0
init_variance: 1.0
start_timestamp: 1606589686447952032
