name: dml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.1
  - _tflow_select=2.1.0
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - appdirs=1.4.4
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=20.3.0
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.2.1
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=3.0.4
  - charls=2.2.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - coverage=5.5
  - cryptography=3.4.7
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.10.0
  - cython=0.29.23
  - cytoolz=0.11.0
  - dask-core=2021.4.0
  - dbus=1.13.6
  - decorator=5.0.7
  - expat=2.3.0
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.4.0
  - gast=0.4.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.1
  - glib-tools=2.68.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.29.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.36.1
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - h5py=2.10.0
  - harfbuzz=2.8.0
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imagecodecs=2021.3.31
  - imageio=2.9.0
  - importlib-metadata=3.10.0
  - intel-openmp=2019.4
  - jasper=1.900.1
  - joblib=1.0.1
  - jpeg=9d
  - jxrlib=1.1
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.1
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libmklml=2019.0.5
  - libopencv=4.5.1
  - libpng=1.6.37
  - libpq=13.1
  - libprotobuf=3.14.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - libzopfli=1.0.3
  - locket=0.2.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - multidict=5.1.0
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - ncurses=6.2
  - nettle=3.6
  - networkx=2.3
  - ninja=1.10.2
  - nspr=4.30
  - nss=3.64
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - opencv=4.5.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - opt_einsum=3.1.0
  - packaging=20.9
  - pandas=1.0.1
  - partd=1.2.0
  - pcre=8.44
  - pillow=8.1.2
  - pip=21.0.1
  - pixman=0.40.0
  - pooch=1.3.0
  - protobuf=3.14.0
  - pthread-stubs=0.4
  - py-opencv=4.5.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-flatbuffers=1.12
  - python_abi=3.8
  - pytorch=1.7.1
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.12.9
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.18.1
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.35.4
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.4.1
  - tensorflow-gpu=2.4.1
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tifffile=2021.4.8
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.60.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - utm=0.6.0
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zfp=0.5.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
